### ISSUE TITLE
start-deployBukkitSpigot, - mv: cant rename 'craftbukkit-*.jar': No such file or directory

### ISSUE THREAD

**Issue by v-mwalk** [itzg/docker-minecraft-server#490]
In start-deployBukkitSpigot, line 23

docker run -d -it -v G:\docker\minecraft:/minecraft -v G:\docker\spigot:/data -e TYPE=SPIGOT -e BUILD_FROM_SOURCE=true  -e VERSION=1.15.2 -e EULA=TRUE -p 25565:25565 -p 25575:25575 -p 8123:8123 --name mc itzg/minecraft-server

**Comment by jpcaldwell30** [comment]
Also having this issue.

**Comment by jw-de** [comment]
The issue starts from version 1.14. Building 1.13.2 works as expected. This seems to be related to a change in the build tools. See the [Spigot Build Tools Wiki Page](https://www.spigotmc.org/wiki/buildtools/):

> You can find CraftBukkit (to but not including version 1.14) and Spigot in the same directory you ran the the BuildTools.jar in (craftbukkit-1.14.jar and spigot-1.14.jar).

**Comment by itzg** [comment]
Thanks for the extra info @jw-de . I recently added a helper function to conditionalize by version, so I can branch the logic there.

**Comment by Thomasolicious** [comment]
I still get this error when trying to run anything above 1.13.2. However I'm fairly new to the principles of github. Is this hotfix something that has been written in the source code of this image or does it require any input from my side when I try to run the docker image for 1.13.2+ to implement this hotfix?

**Comment by itzg** [comment]
@Thomasolicious it's on my part to get that fix applied. I'll update that PR and merge it down...

**Comment by itzg** [comment]
The latest image should resolve this.

**Comment by Thomasolicious** [comment]
I'm still having the same issue, could this be due to something else?

I run this code for the docker:
``docker run -d -v /path/to/data:/data \``
``    -e TYPE=BUKKIT -e VERSION=LATEST \``
``    -e TZ=Europe/Amsterdam -e BUILD_FROM_SOURCE=true \``
``    -p 25565:25565 -e EULA=TRUE --name name itzg/minecraft-server --noconsole``

With ofcourse the path to the data being the specific path of my filesystem but I left that out of the above.

Response:
``[init] Changing ownership of /data to 1000 ...``
``[init] Running as uid=1000 gid=1000 with /data as 'drwxrwsr-x    1 1000     1000            16 May 12 18:30 /data'``
``[init] Resolved version given LATEST into 1.15.2``
``[init] Resolving type given BUKKIT``
``[init] Building Spigot 1.15.2 from source, might take a while, get some coffee``
``[init] .......................[init] done``
``mv: can't rename 'craftbukkit-*.jar': No such file or directory``

Here I left the majority of the dots out because otherwise this comment would have been overloaded with dots.

**Comment by itzg** [comment]
@Thomasolicious , please do a `docker pull` to double check you have the latest image. Since craftbukkit is no longer built starting with 1.14, the latest image includes logic to detect that combination and fails before the lengthy build:

```
> docker run -it --rm -e TYPE=BUKKIT -e VERSION=LATEST -e BUILD_FROM_SOURCE=true -e EULA=TRUE itzg/minecraft-server --noconsole
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 May 12 21:33 /data'
[init] Resolved version given LATEST into 1.15.2
[init] Resolving type given BUKKIT
[init] ERR craftbukkit build is only supported for versions less than 1.14
```

If you change to `TYPE=SPIGOT`, then the build proceeds and server starts as expected.

**Comment by Thomasolicious** [comment]
Ok I thought I tried spigot the other day and it also wouldn't work. This time around it did work, thanks a lot!
